/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeReferralsRouteImport } from './routes/trade-referrals'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReportSampleRouteImport } from './routes/report-sample'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as IndexRouteImport } from './routes/index'

const TradeReferralsRoute = TradeReferralsRouteImport.update({
  id: '/trade-referrals',
  path: '/trade-referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSampleRoute = ReportSampleRouteImport.update({
  id: '/report-sample',
  path: '/report-sample',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/pricing': typeof PricingRoute
  '/report-sample': typeof ReportSampleRoute
  '/services': typeof ServicesRoute
  '/trade-referrals': typeof TradeReferralsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/pricing': typeof PricingRoute
  '/report-sample': typeof ReportSampleRoute
  '/services': typeof ServicesRoute
  '/trade-referrals': typeof TradeReferralsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/pricing': typeof PricingRoute
  '/report-sample': typeof ReportSampleRoute
  '/services': typeof ServicesRoute
  '/trade-referrals': typeof TradeReferralsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreement'
    | '/pricing'
    | '/report-sample'
    | '/services'
    | '/trade-referrals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreement'
    | '/pricing'
    | '/report-sample'
    | '/services'
    | '/trade-referrals'
  id:
    | '__root__'
    | '/'
    | '/agreement'
    | '/pricing'
    | '/report-sample'
    | '/services'
    | '/trade-referrals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementRoute: typeof AgreementRoute
  PricingRoute: typeof PricingRoute
  ReportSampleRoute: typeof ReportSampleRoute
  ServicesRoute: typeof ServicesRoute
  TradeReferralsRoute: typeof TradeReferralsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-referrals': {
      id: '/trade-referrals'
      path: '/trade-referrals'
      fullPath: '/trade-referrals'
      preLoaderRoute: typeof TradeReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-sample': {
      id: '/report-sample'
      path: '/report-sample'
      fullPath: '/report-sample'
      preLoaderRoute: typeof ReportSampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementRoute: AgreementRoute,
  PricingRoute: PricingRoute,
  ReportSampleRoute: ReportSampleRoute,
  ServicesRoute: ServicesRoute,
  TradeReferralsRoute: TradeReferralsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
